import os
import subprocess
import sys

# ==========================
# Base directory of the project
# ==========================
BASE_DIR = os.path.dirname(os.path.abspath(__file__))

# ==========================
# Project folder structure
# Designed for enterprise-level ML project
# ==========================
FOLDERS = [
    # --------------------------
    # Data layers
    # --------------------------
    "data/bronze",    # Raw ingested data
    "data/silver",    # Cleaned / processed data
    "data/gold",      # Curated / feature-ready data

    # --------------------------
    # Notebooks
    # --------------------------
    "notebooks",
    "notebooks/archive",  # Archive for old notebooks

    # --------------------------
    # Source code organized by functionality
    # --------------------------
    "src/ingestion",    # Scripts to load or ingest data
    "src/features",     # Feature engineering scripts
    "src/models",       # Model training scripts
    "src/evaluation",   # Model evaluation scripts
    "src/genai",        # Generative AI / LLM code
    "src/dq",           # Data quality checks

    # --------------------------
    # Tools and apps
    # --------------------------
    "mlflow",           # MLflow experiment tracking
    "streamlit_app",    # Streamlit app for dashboards or apps

    # --------------------------
    # Metadata, configs, and logs
    # --------------------------
    "meta",             # Metadata files / schemas
    "config",           # Configuration files (YAML/JSON)
    "logs",             # Logs generated by scripts
    "reports",          # Reports and summaries
    "artifacts",        # Saved models, outputs, serialized files

    # --------------------------
    # Project management
    # --------------------------
    "tests",                  # Unit and integration tests
    ".github/workflows",      # CI/CD GitHub actions
    "docs",                   # Documentation

    # --------------------------
    # Optional enterprise-level folders
    # --------------------------
    "scripts",      # Standalone helper scripts
    "deploy",       # Deployment scripts / Docker / K8s
    "examples",     # Example notebooks or demos
    "assets",       # Images, static resources, or report templates
]

# ==========================
# Function to create folders
# ==========================
def create_folders():
    """
    Create all folders listed in FOLDERS under BASE_DIR.
    Existing folders are skipped without error.
    """
    for folder in FOLDERS:
        folder_path = os.path.join(BASE_DIR, folder)
        os.makedirs(folder_path, exist_ok=True)
        print(f"Created folder: {folder_path}")

# ==========================
# Function to create essential project files
# ==========================
def create_files():
    """
    Create essential project files if missing:
    - README.md: Project overview
    - .gitignore: Git ignore rules
    - requirements.txt: Python dependencies
    - .env.example: Environment variables template
    - config/config.yaml: Project configuration
    """
    files = {
        "README.md": (
            "# AML Transaction Monitoring System\n\n"
            "Enterprise-grade Anti-Money Laundering detection system using ML and GenAI.\n\n"
            "## Project Structure\n"
            "- data/: raw, processed, and curated datasets\n"
            "- src/: source code for ingestion, features, modeling, evaluation, GenAI\n"
            "- notebooks/: Jupyter notebooks\n"
            "- logs/, artifacts/, reports/: outputs and logs\n"
        ),
        ".gitignore": (
            "# --------------------------\n"
            "# Environment variables\n"
            "# --------------------------\n"
            "# Do not commit .env files, they contain sensitive API keys\n"
            ".env\n"
            ".venv\n"
            ".VENV\n"
            ".env.*\n\n"

            "# --------------------------\n"
            "# Data\n"
            "# --------------------------\n"
            "data/\n*.csv\n*.parquet\n\n"

            "# --------------------------\n"
            "# Python artifacts\n"
            "# --------------------------\n"
            "__pycache__/\n*.pyc\nvenv/\n.venv/\n\n"

            "# --------------------------\n"
            "# MLflow\n"
            "# --------------------------\n"
            "mlflow/\n\n"

            "# --------------------------\n"
            "# Jupyter\n"
            "# --------------------------\n"
            ".ipynb_checkpoints/\n\n"

            "# --------------------------\n"
            "# IDE / Editor\n"
            "# --------------------------\n"
            ".vscode/\n\n"

            "# --------------------------\n"
            "# Logs, artifacts, reports\n"
            "# --------------------------\n"
            "logs/\nartifacts/\nreports/\n"
        ),
        "requirements.txt": (
            "# --------------------------\n"
            "# Data processing\n"
            "pandas==2.2.2\nnumpy==1.26.4\npyarrow==15.0.2\n\n"

            "# --------------------------\n"
            "# Machine Learning\n"
            "scikit-learn==1.4.2\nxgboost==2.0.3\nimbalanced-learn==0.12.2\n\n"

            "# --------------------------\n"
            "# Experiment tracking\n"
            "mlflow==2.12.1\n\n"

            "# --------------------------\n"
            "# Explainability\n"
            "shap==0.45.0\n\n"

            "# --------------------------\n"
            "# Visualization\n"
            "matplotlib==3.8.4\nseaborn==0.13.2\nplotly==5.21.0\n\n"

            "# --------------------------\n"
            "# Dashboard\n"
            "streamlit==1.33.0\n\n"

            "# --------------------------\n"
            "# GenAI / LLM\n"
            "openai==1.25.0\nanthropic==0.25.0\n\n"

            "# --------------------------\n"
            "# Utilities\n"
            "python-dotenv==1.0.1\njoblib==1.4.0\n"
        ),
        ".env.example": (
            "# Copy this file to .env and fill in your API keys\n"
            "# NEVER commit .env to GitHub\n\n"
            "OPENAI_API_KEY=your_openai_api_key_here\n"
            "ANTHROPIC_API_KEY=your_anthropic_api_key_here\n"
        ),
        "config/config.yaml": (
            "# AML Project Configuration\n\n"
            "project:\n"
            "  name: AML Transaction Monitoring System\n"
            "  version: 1.0.0\n\n"
            "data:\n"
            "  raw_file: data/bronze/transactions.csv\n"
            "  silver_path: data/silver/\n"
            "  gold_path: data/gold/\n\n"
            "model:\n"
            "  test_size: 0.2\n"
            "  random_state: 42\n"
            "  threshold: 0.5\n\n"
            "mlflow:\n"
            "  experiment_name: aml-fraud-detection\n"
        ),
    }

    for filename, content in files.items():
        file_path = os.path.join(BASE_DIR, filename)
        # Ensure parent directories exist
        os.makedirs(os.path.dirname(file_path), exist_ok=True)
        if not os.path.exists(file_path):
            with open(file_path, "w") as f:
                f.write(content)
            print(f"Created file: {file_path}")
        else:
            print(f"File exists, skipped: {file_path}")

# ==========================
# Function to create Python virtual environment
# ==========================
def create_venv():
    """
    Create a Python virtual environment named 'venv' in the project root.
    Ensures project dependencies are isolated.
    """
    venv_path = os.path.join(BASE_DIR, "venv")
    if not os.path.exists(venv_path):
        print("Creating virtual environment...")
        subprocess.run([sys.executable, "-m", "venv", venv_path], check=True)
        print(f"Virtual environment created at: {venv_path}")
        print("Activate it using: source venv/bin/activate (Linux/macOS) or venv\\Scripts\\activate (Windows)")
    else:
        print("Virtual environment exists, skipped.")

# ==========================
# Function to add .gitkeep files to empty folders
# ==========================
def create_gitkeep():
    """
    Add a .gitkeep file to every folder to allow Git to track empty directories.
    Skips folders that already have a .gitkeep file.
    """
    for folder in FOLDERS:
        folder_path = os.path.join(BASE_DIR, folder)
        gitkeep_path = os.path.join(folder_path, ".gitkeep")
        if not os.path.exists(gitkeep_path):
            with open(gitkeep_path, "w"):
                pass
            print(f"Added .gitkeep: {gitkeep_path}")
        else:
            print(f".gitkeep exists, skipped: {gitkeep_path}")

# ==========================
# Script entry point
# ==========================
if __name__ == "__main__":
    create_folders()    # Step 1: Create all project folders
    create_files()      # Step 2: Create essential project files
    create_venv()       # Step 3: Create isolated Python environment
    create_gitkeep()    # Step 4: Add .gitkeep files to empty folders